Kustomise


Create a base directory for each application with the default configuration.

Create an overlays directory with subdirectories for each cluster.

Use kustomization.yaml in each overlay to reference the base configurations and any cluster-specific customizations.

apps/
├── app1/
│   ├── base/
│   │   ├── deployment.yaml
│   │   └── kustomization.yaml
│   └── overlays/
│       ├── cluster1/
│       │   ├── kustomization.yaml
│       │   └── patches.yaml
│       └── cluster2/
│           ├── kustomization.yaml
│           └── patches.yaml
├── app2/
│   ├── base/
│   │   ├── deployment.yaml
│   │   └── kustomization.yaml
│   └── overlays/
│       ├── cluster1/
│       │   ├── kustomization.yaml
│       │   └── patches.yaml
│       └── cluster2/
│           ├── kustomization.yaml
│           └── patches.yaml



apps/app1/base/kustomization.yaml
resources:
  - deployment.yaml

apps/app2/base/kustomization.yaml
resources:
  - deployment.yaml

  
kubectl apply -k apps/app1/overlays/cluster1
kubectl apply -k apps/app1/overlays/cluster2

for app in app1 app2; do
  for cluster in cluster1 cluster2; do
    kubectl apply -k apps/$app/overlays/$cluster
  done
done














  




