Several blogs mention that people need to combine ALB ingress and Nginx ingress controller for the following reasons

1. Using the nginx ingress controller, we cannot directly connect to an ALB
2. Each ingress resource in the cluster will have its own ALB instance if we only use the ALB ingress controller

I disagree with the statement above.

The following points need to be highlighted based on the testing we conducted on each ingress controller separately

1. Nginx ingress and alb ingress with eks have been tested separately.
2. Both ingress controllers worked with existing albs.
3. The Alb Ingress controller worked with ClusterIP in the ingress resource.
4. The Nginx Controller that worked with Nodeports in an Ingress resource.
5. The ingress resource and service do not require their own albs.
6. There are a few advanced points that need to be tested.
a. SSL Termination.
b. Path-Based Routing
