image:
  repository: tiangolo/uvicorn-gunicorn-fastapi
  tag: python3.9
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

app: 
  command: ["uvicorn"]
  args: ["main:app", "--host=0.0.0.0", "--port=80"]

volumeMounts: []
volumes: []

containerPorts:
  http: 80

