In this lesson, we will see the differences between a NodePort service and a ClusterIP 
service and see how the iptables rules take effect when traffic is coming in


cat sample.yml

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx


Get the services YAML output for all the services in your cluster

kubectl get services -o yaml

Try and ping the clusterIP service IP address:

ping 10.96.0.1


View the list of endpoints in your cluster that get created with a service:

kubectl get endpoints


Look at the iptables rules for your services:

iptables-save | grep KUBE | grep nginx





