apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - image: mongo
    name: mongo
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
    ports:
    - conatinerPort: 27017
      protocol: TCP
    volumes:
    - name: mongo-data
      persistentVolumeClaim:
        claimName: mongodb-pvc



