[cmd]

[command to run an alpine container with default security]

kubectl run pod-with-defaults --image alpine --restart Never -- /bin/sleep 999999

[check the ID on the container]

kubectl exec pod-with-defaults id



[yaml to create pod as root user]

cat root-test.yml

apiVersion: v1
kind: Pod
metadata:
  name: alpine-user-context
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 405


[yaml to create pod as non-root user]      


cat privilege.yaml      
      
apiVersion: v1
kind: Pod
metadata:
  name: alpine-nonroot
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsNonRoot: true


[yaml to create pod as privilege user]


cat privilege.yaml

apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      privileged: true


[View the devices on the default container]


kubectl exec -it pod-with-defaults ls /dev


[View the devices on the privileged pod container]


kubectl exec -it privileged-pod ls /dev



[command change the time on a default container pod]


kubectl exec -it pod-with-defaults -- date +%T -s "12:00:00"




vim time.yml


apiVersion: v1
kind: Pod
metadata:
  name: kernelchange-pod
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      capabilities:
        add:
        - SYS_TIME


          













