version: '2.4'

networks:
  monitoring_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.23.0/24
          gateway: 172.32.23.1

volumes:
  esdata:

services:

  prometheus:
    image: prom/prometheus:v2.51.2
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
    networks:
      monitoring_bridge:
        ipv4_address: 172.32.23.2
    restart: always

  grafana:
    image: grafana/grafana:13.0.1-security-01
    depends_on:
      - prometheus
    ports:
      - 3007:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      monitoring_bridge:
        ipv4_address: 172.32.23.3
    restart: always

  node_exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - 9100:9100
    networks:
      monitoring_bridge:
        ipv4_address: 172.32.23.4
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.100.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317
      - 4318:4318
      - 9999:9999
    networks:
      monitoring_bridge:
        ipv4_address: 172.32.23.6
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.26.0
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--cluster.listen-address='
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      monitoring_bridge:
        ipv4_address: 172.32.23.7
    restart: always

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    ports:
      - 9115:9115
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      monitoring_bridge:
        ipv4_address: 172.32.23.8
    restart: always

