input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  # optional parsing
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "otel-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
