
Core Concepts (13%)
Practice questions based on these concepts
Understand Kubernetes API Primitives
Create and Configure Basic Pods

1.How to List all the namespaces in the cluster??

kubectl get namespaces
kubectl get ns

2.How to List all the pods in all namespaces ??

kubectl get po --all-namespaces

3.How to List all the services in the particular namespace

kubectl get svc -n <namespace name>

4.List all the pods showing name and namespace with a json path expression

kubectl get pods -o=jsonpath="{.items[*]['metadata.name', 'metadata.namespace']}"

5.How to Create an nginx pod in a default namespace and verify the pod running?

kubectl run nginx --image=nginx --restart=Never

kubectl get po

6.Create the same nginx pod with a yaml file

kubectl run nginx --image=nginx --restart=Never --dry-run -o yaml > nginx-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
// create a pod 

kubectl create -f nginx-pod.yaml

8.how to Output the yaml file of the pod you just created?
kubectl get po nginx -o yaml

9.How to Output the yaml file of the pod you just created without the cluster-specific information?

kubectl get po nginx -o yaml --export


10.How to Get the complete details of the pod you just created?
kubectl describe pod nginx

11.How to Delete the pod you just created?
kubectl delete po nginx
kubectl delete -f nginx-pod.yaml


12.How to Delete the pod you just created without any delay (force delete)??
kubectl delete po nginx --grace-period=0 --force

13.How to  Create the nginx pod with version 1.17.4 and expose it on port 80?
kubectl run nginx --image=nginx:1.17.4 --restart=Never --port=80


14.How to Change the Image version to 1.15-alpine for the pod you just created and verify the image version is updated??

kubectl set image pod/nginx nginx=nginx:1.15-alpine
kubectl describe po nginx
// another way it will open vi editor and change the version
kubeclt edit po nginx
kubectl describe po nginx


15. How to Change the Image version back to 1.17.1 for the pod you just updated and observe the changes??
kubectl set image pod/nginx nginx=nginx:1.17.1
kubectl describe po nginx
kubectl get po nginx -w # watch it

16.How to Check the Image version without the describe command??
kubectl get po nginx -o jsonpath='{.spec.containers[].image}{"\n"}'

17.Create the nginx pod and execute the simple shell on the pod
kubectl run nginx --image=nginx --restart=Never
kubectl exec -it nginx /bin/sh


18.How to Get the IP Address of the pod you just created??
kubectl get po nginx -o wide

19.How to Create a busybox pod and run command ls while creating it and check the logs??
kubectl run busybox --image=busybox --restart=Never -- ls
kubectl logs busybox

20.How If pod crashed check the previous logs of the pod?
kubectl logs busybox -p

21.How to Create a busybox pod with command sleep 3600??
kubectl run busybox --image=busybox --restart=Never -- /bin/sh -c "sleep 3600"

22.How to Check the connection of the nginx pod from the busybox pod??
kubectl exec -it busybox -- wget -o- <IP Address>

23.How to Create a busybox pod and echo message ‘How are you’ and delete it manually??
kubectl run busybox --image=nginx --restart=Never -it -- echo "How are you"

24.How to Create a busybox pod and echo message ‘How are you’ and have it deleted immediately??
kubectl run busybox --image=nginx --restart=Never -it --rm -- echo "How are you"

25.How to Create an nginx pod and list the pod with different levels of verbosity
// create a pod
kubectl run nginx --image=nginx --restart=Never --port=80
// List the pod with different verbosity
kubectl get po nginx --v=7
kubectl get po nginx --v=8
kubectl get po nginx --v=9

26.List the nginx pod with custom columns POD_NAME and POD_STATUS
kubectl get po -o=custom-columns="POD_NAME:.metadata.name, POD_STATUS:.status.containerStatuses[].state"

27.How to List all the pods sorted by name??
kubectl get pods --sort-by=.metadata.name

28.How to List all the pods sorted by created timestamp??
kubectl get pods--sort-by=.metadata.creationTimestamp
















