There are ways Kubernetes can automatically monitor your apps for you and, furthermore,
fix them by either restarting or preventing them from affecting the rest of your service.
You can insert liveness probes and readiness probes to do just this for custom monitoring of your applications.

The pod YAML for a liveness probe:

apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - image: linuxacademycontent/kubeserve
    name: kubeserve
    livenessProbe:
      httpGet:
        path: /
        port: 80


Create the service and two pods with readiness probes:

kubectl apply -f readiness.yaml
Check if the readiness check passed or failed:

kubectl get pods
Check if the failed pod has been added to the list of endpoints:

kubectl get ep
Edit the pod to fix the problem and enter it back into the service:

kubectl edit pod [pod_name]
Get the list of endpoints to see that the repaired pod is part of the service again:

kubectl get ep



