apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: app
    tier: frontend
spec: 
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metdata:
      labels: 
        tier: frontend
    spec:
      conatiners:      
      - name: main
        image: linuxacademycontent/kubeserve
        
