apiVersion: v1
kind: Pod
metadata: 
  name: my-sa-pod
spec:
  serviceAccountName: my-sa
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo hello,api! && sleep 3600"]

