```yaml
apiVersion: v1
kind: Secret

metadata:
  name: grafana-backup-secret
  namespace: default

type: Opaque

stringData:

  # =====================================================
  # GRAFANA API KEYS
  # =====================================================

  PROD_GRAFANA_API_KEY: "prod-api-key"

  TEST_GRAFANA_API_KEY: "test-api-key"

  SYST_GRAFANA_API_KEY: "syst-api-key"

  # =====================================================
  # AWS
  # =====================================================

  AWS_ACCESS_KEY_ID: "xxxxxxxx"

  AWS_SECRET_ACCESS_KEY: "xxxxxxxx"

  AWS_DEFAULT_REGION: "ap-south-1"

  # =====================================================
  # OPTIONAL S3 BUCKET
  # =====================================================

  S3_BUCKET_NAME: "grafana-backup-bucket"

