apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: lab
spec:  
  stoargeClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

