
wget https://kubernetes.io/examples/pods/pod-configmap-volume.yaml
wget https://kubernetes.io/examples/configmap/configmap-multikeys.yaml
wget https://kubernetes.io/examples/pods/pod-configmap-env-var-valueFrom.yaml
wget https://kubernetes.io/examples/pods/pod-configmap-envFrom.yaml
wget https://kubernetes.io/examples/configmap/configmap-multikeys.yaml
wget https://kubernetes.io/examples/pods/pod-multiple-configmap-env-variable.yaml
wget https://kubernetes.io/examples/configmap/configmaps.yaml
wget https://kubernetes.io/examples/pods/pod-single-configmap-env-variable.yaml
wget https://kubernetes.io/examples/configmap/ui-env-file.properties 
wget https://kubernetes.io/examples/configmap/game-env-file.properties -O configure-pod-container/configmap/game-env-file.properties
wget https://kubernetes.io/examples/configmap/game.properties -O configure-pod-container/configmap/game.properties
wget https://kubernetes.io/examples/configmap/ui.properties -O configure-pod-container/configmap/ui.properties
