
wget https://kubernetes.io/examples/pods/pod-configmap-volume.yaml
wget https://kubernetes.io/examples/configmap/configmap-multikeys.yaml
wget https://kubernetes.io/examples/pods/pod-configmap-env-var-valueFrom.yaml
wget https://kubernetes.io/examples/pods/pod-configmap-envFrom.yaml
wget https://kubernetes.io/examples/configmap/configmap-multikeys.yaml
wget https://kubernetes.io/examples/pods/pod-multiple-configmap-env-variable.yaml
wget https://kubernetes.io/examples/configmap/configmaps.yaml
wget https://kubernetes.io/examples/pods/pod-single-configmap-env-variable.yaml
wget https://kubernetes.io/examples/configmap/ui-env-file.properties 
wget https://kubernetes.io/examples/configmap/game-env-file.properties 
wget https://kubernetes.io/examples/configmap/game.properties 
wget https://kubernetes.io/examples/configmap/ui.properties 
wget https://kubernetes.io/examples/pods/pod-configmap-volume-specific-key.yaml
https://github.com/VictoriaMetrics/VictoriaMetrics

k8s.gcr.io/busybox

kubectl create configmap game-config --from-file=ui.properties
kubectl create configmap game-configmap-env --from-env-file=game-env-file.properties

kubectl create configmap special-config --from-literal=redmi=phone --from-literal=alexa=ai


How to mount configmap literal value inside of pod ??

apiVersion: v1
kind: Pod
metadata:
  name: busy1
spec:
  containers:
  - image: tomcat:8.0
    name: busy
    env:
      - name: CONF_VAL
        valueFrom:
          configMapKeyRef:
           name: special-config
           key: redmi
  restartPolicy: Never
  
  
 
 
 
Volume Mounted 
 
How to mount configmap file inside of pod directory??
kubectl create configmap game-config --from-file=ui.properties


root@k8i:~/cm# cat b16.yml 
apiVersion: v1
kind: Pod
metadata:
  name: busy3
spec:
  containers:
  - image: tomcat:8.0
    name: busy
    #command: ["/bin/bash", "-c", "ls /usr/local/tomcat"]
    volumeMounts:
    - name: config-volume
      mountPath: /usr/local/tomcat/webapps
          
  volumes:
    - name: config-volume
      configMap: 
        name: game-config


  cat conf/context.xml
  /usr/local/tomcat
  
  LICENSE  NOTICE  RELEASE-NOTES	RUNNING.txt  bin  conf	include  lib  logs  native-jni-lib  temp  webapps  work
  
  
  How to create a secret from files
  
  echo -n 'admin' > user.txt
  echo -n 'admin123' > pass.txt
  
  kubectl create secret generic db-pass --from-file=user.txt --from-file=pass.txt
  
  How to decode the secret??
  
  kubectl get secret db-pass -o yaml > d2.yml
  echo 'YWRtaW4xMjM=' | base64 --decode


How to inject secret files in to pod??
  
  
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
  - image: redis
    name: my-pod-1
    volumeMounts:
    - mountPath: "/etc/foo" 
      name: foo
      
  volumes:
  - name: foo
    secret:
      secretName: db-pass
 
  
  Projection of Secret keys to specific paths  na
  
  
  How to use secret as an environment variable??
  
  How to set permission on secret in pod??
  
  
  How to create a Pod which references the secret with the ssh key and consumes it in a volume?
   
   
How to   use dotfile as secret? 
  
  
  
  
