rce 1. Write a CronJob which prints some text to the console every minute
2. Write a Job which will print computes Ï€ to 2000 places and prints it out
kind: Job
metadata:
  name: hello9
spec:
  templates:     
    spec:
      containers:
      - image: perl
        name: pi
        command: ["perl", "-Mbignum=bpi" , "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4


3. Write cron job  which will prints the current time and a hello message every minute
kubectl run helo --image=tomcat:8.0
kubectl get po helo -o yaml > cr.yml

kubectl run hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c "date;echo Hello from the Kubernetes cluster"
#above mentioned command not worked

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helo5

spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: tomcat:8.0
            name: helo5
            command: ["bash", "-c", "echo 'testing'"]
          restartPolicy:  OnFaliure




4. Write a Job which will be eligible to be automatically deleted,  after 100 seconds once it get finish 


apiVersion: batch/v1
kind: Job
metadata:
  name: hello7
spec:
  ttlSecondsAfterFinish: 100
  template:
    spec:
      containers:    
      - image: tomcat:8.0
        name: hello7
        command: ["bash", "-c", "echo 'test'"]
      restartPolicy: OnFaliure 



https://www.magalix.com/blog/kubernetes-patterns-the-cron-job-pattern
