1. Create a nginx  Deployment by declarative and imperative way
2. Update the nginx deployment with record from version 1.7.9 to 1.9.1
3. Check Rollout status of nginx deployment
4. Check Rolling history of nginx deployment
5. Undo roll back to previous previous version 2
6. Implement Vertical Scale out of nginx  deployment by 4 replicas
7. Implement Vertical Scale in of nginx deployment by 2 replicas
8. Implement Horizontal Autoscale By of nginx deployment  cpu-perecent 60%


