
1.Create a pod with two labels environment: prod and app: nginx
kubectl run tomcat --image=tomcat:8.0
2.create a pod with nodeSelector: dev

kubectl label nodes k8i dev=true
kubectl get nodes -l dev=true


apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: nginx
    environment: prod
spec:
  containers:
  - image: tomcat:8.0
    name: tomcat
  nodeSelector:
    dev: "true"




3.Create a pod with annotations owner: nik 

apiVersion: v1
kind: Pod
metadata:
  name: tomcat     
  annotations:
    owner: nik     
spec:
  containers:
  - image: tomcat:8.0
    name: tomcat


4.Configure deployment with PodAntiAffinity to ensure scheduler does not co-locate replicas on a single node

