apiVersion: v1
kind: Pod
metadata:
  name: voulume-pod
spec:
  containers:
  - image: busybox
    name: busybox
    commansd: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts: 
    - name: my-volume
      mountPath: /tmp/storage
    volumes:
    - name: my-volume
      emptyDir: {}

