apiVersion: v1
kind: Pod
metadata: 
  name: mongo-pod
  namespace: lab
spec:
  containers:
  - image: mongo
    name: mongo-pod
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
  ports:  
  - containerPort: 27017
    protocol: TCP
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      ClaimName: mongo-pvc



