# -------- Service identity --------
otel.service.name=hello-app
otel.resource.attributes=hostname=controller

# -------- Export interval --------
otel.metric.export.interval=5000

# -------- Exporters --------
#otel.traces.exporter=otlp
#otel.metrics.exporter=otlp
otel.logs.exporter=otlp

# -------- Agent log level --------
otel.javaagent.debug=true

# -------- OTLP endpoint --------
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf

# -------- Headers --------
otel.exporter.otlp.headers=authorization=bearer test123

# -------- Capture headers in traces --------
otel.instrumentation.http.capture-headers.server.request=*
otel.instrumentation.http.capture-headers.server.response=*

